[package]
name = "modulus_regex"
version = "0.1.0"
edition = "2024"

[lib]
name = "lib"
crate-type = ["cdylib", "rlib"]

[dependencies]
rand = "0.9.2"
regex = "1.12.2"
wasm-bindgen = "0.2.106"
getrandom = { version = "0.3", features = ["wasm_js"] }

[[bin]]
name = "modulus_bin"
path = "src/main.rs"